In [74]:
#Imports used
import numpy as np
import matplotlib as plt
import pandas as pd

In [5]:
space_missions = pd.read_csv("original/all_space_mission_launches.csv")
space_missions

,Unnamed: 0,Organisation,Location,Datetime,Details,Rocket_Status,Price,Mission_Status
0,0,VKS RF,"Site 43/4, Plesetsk Cosmodrome, Russia","Fri Feb 09, 2024 07:03 UTC",Soyuz 2.1v | Cosmos 2575,Active,NaN,Success
1,1,SpaceX,"SLC-40, Cape Canaveral SFS, Florida, USA","Thu Feb 08, 2024 06:33 UTC",Falcon 9 Block 5 | PACE,Active,67.0,Success
2,2,CASC,"Bo Run Jiu Zhou Barge (Area 2), China Coastal ...","Sat Feb 03, 2024 03:06 UTC",Jielong-3 | 9 satellites,Active,NaN,Success
3,3,CASC,"LC-3, Xichang Satellite Launch Center, China","Fri Feb 02, 2024 23:37 UTC",Long March 2C | Geely Constellation Group 02,Active,30.8,Success
4,4,Rocket Lab,"Rocket Lab LC-1B, Māhia Peninsula, New Zealand","Wed Jan 31, 2024 06:34 UTC",Electron/Curie | Four Of A Kind,Active,7.5,Success
...,...,...,...,...,...,...,...,...
6706,706,US Navy,"LC-18A, Cape Canaveral SFS, Florida, USA","Wed Feb 05, 1958 07:33 UTC",Vanguard | Vanguard TV3BU,Retired,NaN,Failure
6707,707,ABMA,"LC-26A, Cape Canaveral SFS, Florida, USA","Sat Feb 01, 1958 03:47 UTC",Juno I | Explorer 1,Retired,NaN,Success
6708,708,US Navy,"LC-18A, Cape Canaveral SFS, Florida, USA","Fri Dec 06, 1957 16:44 UTC",Vanguard | Vanguard TV3,Retired,NaN,Failure
6709,709,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Sun Nov 03, 1957 02:30 UTC",Sputnik 8K71PS | Sputnik 2,Retired,NaN,Success
6710,710,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Fri Oct 04, 1957 19:28 UTC",Sputnik 8K71PS | Sputnik 1,Retired,NaN,Success

The first thing that I notice is the **unnamed column**, which does not follow the same numerical principle as the row ranking in bold. Upon further investigation, it seems that the row count begins anew for a total of 5 times on rows 300, 1500, 3000, 4500, 6000. **Can't find if there is any logic or method to the unnamed counter**. All of the columns contain different information; there are some values which repeat, but it's not due to an error or pattern of any kind. I checked the table in excel, to see if maybe the row count corresponds to some kind of date/ year logic, but I couldn't find any. Since this column doesn't serve any purpose or provide any logic, I will **delete it from the dataset**.

In [6]:
# Input
target = 0
col = "Unnamed: 0"

windows = []

# Logic
# Logic for the # times 0 appears and on which row
count_of_0 = (space_missions["Unnamed: 0"] == target).sum()
rows_where_0 = space_missions.index[space_missions["Unnamed: 0"] == target].tolist()

# Print result
print(count_of_0, rows_where_0)

6 [0, 300, 1500, 3000, 4500, 6000]

In [30]:
space_missions.iloc[300:310]

,Unnamed: 0,Organisation,Location,Datetime,Details,Rocket_Status,Price,Mission_Status
300,0,Roscosmos,"Site 31/6, Baikonur Cosmodrome, Kazakhstan","Wed Oct 26, 2022 00:20 UTC",Soyuz 2.1a | Progress MS-21,Active,17.42,Success
301,1,Roscosmos,"Site 1S, Vostochny Cosmodrome, Russia","Sat Oct 22, 2022 19:57 UTC",Soyuz 2.1b/Fregat-M | Goniets-M n°33L to 35L &...,Active,25.00,Success
302,2,ISRO,"Second Launch Pad, Satish Dhawan Space Centre,...","Sat Oct 22, 2022 18:37 UTC",LVM-3 | OneWeb #14,Active,62.00,Success
303,3,VKS RF,"Site 43/4, Plesetsk Cosmodrome, Russia","Fri Oct 21, 2022 19:20 UTC",Soyuz 2.1v/Volga | Cosmos 2561 & 2562,Active,NaN,Success
304,4,SpaceX,"SLC-40, Cape Canaveral SFS, Florida, USA","Thu Oct 20, 2022 14:50 UTC",Falcon 9 Block 5 | Starlink Group 4-36,Active,67.00,Success
305,5,VKS RF,"Site 35/1, Plesetsk Cosmodrome, Russia","Sat Oct 15, 2022 19:55 UTC",Angara 1.2 | Cosmos 2560,Active,NaN,Success
306,6,SpaceX,"SLC-40, Cape Canaveral SFS, Florida, USA","Sat Oct 15, 2022 05:22 UTC",Falcon 9 Block 5 | Hotbird 13F,Active,67.00,Success
307,7,CASC,"LC-3, Xichang Satellite Launch Center, China","Fri Oct 14, 2022 19:12 UTC",Long March 2D | Yaogan 36 Group 02,Active,29.75,Success
308,8,CASC,"LC-9, Taiyuan Satellite Launch Center, China","Wed Oct 12, 2022 22:53 UTC",Long March 2C | 5 m S-SAR-01 (Huanjing-2E),Active,30.80,Success
309,9,Roscosmos,"Site 81/24, Baikonur Cosmodrome, Kazakhstan","Wed Oct 12, 2022 15:00 UTC",Proton-M/DM-3 | Angosat-2,Active,65.00,Success

In [31]:
space_missions.iloc[1500:1510]

,Unnamed: 0,Organisation,Location,Datetime,Details,Rocket_Status,Price,Mission_Status
1500,0,ULA,"SLC-2W, Vandenberg SFB, California, USA","Fri Oct 28, 2011 09:48 UTC",Delta II 7920-10C | Suomi NPP / ELaNa III,Retired,NaN,Success
1501,1,Arianespace,"ELS, Guiana Space Centre, French Guiana, France","Fri Oct 21, 2011 10:30 UTC",Soyuz ST-B/Fregat-MT | Galileo IOV FM01-FM02,Active,30.00,Success
1502,2,ILS,"Site 200/39, Baikonur Cosmodrome, Kazakhstan","Wed Oct 19, 2011 18:48 UTC",Proton-M/Briz-M | ViaSat-1,Active,65.00,Success
1503,3,ISRO,"First Launch Pad, Satish Dhawan Space Centre, ...","Wed Oct 12, 2011 05:31 UTC",PSLV-CA | Megha-Tropiques & Others,Active,21.00,Success
1504,4,CASC,"LC-2, Xichang Satellite Launch Center, China","Fri Oct 07, 2011 08:21 UTC",Long March 3B/E | Eutelsat W3C,Active,29.15,Success
1505,5,Land Launch,"Site 45/1, Baikonur Cosmodrome, Kazakhstan","Wed Oct 05, 2011 21:00 UTC",Zenit-3 SLB | Intelsat 18,Retired,NaN,Success
1506,6,VKS RF,"Site 43/4, Plesetsk Cosmodrome, Russia","Sun Oct 02, 2011 20:15 UTC",Soyuz 2.1b/Fregat-M | Cosmos 2474,Active,25.00,Success
1507,7,ILS,"Site 200/39, Baikonur Cosmodrome, Kazakhstan","Thu Sep 29, 2011 18:31 UTC",Proton-M/Briz-M | QuetzSat-1,Active,65.00,Success
1508,8,CASC,"Site 901 (SLS-1), Jiuquan Satellite Launch Cen...","Thu Sep 29, 2011 13:16 UTC",Long March 2F/T | Tiangong-1,Active,NaN,Success
1509,9,Northrop,"LP-1, Pacific Spaceport Complex, Kodiak, Alask...","Tue Sep 27, 2011 15:49 UTC",Minotaur IV | TacSat-4,Active,46.00,Success

In [33]:
space_missions.iloc[3000:3010]

,Unnamed: 0,Organisation,Location,Datetime,Details,Rocket_Status,Price,Mission_Status
3000,0,Martin Marietta,"SLC-4E, Vandenberg SFB, California, USA","Fri Nov 08, 1991 07:07 UTC",Titan IV(403)A | SLDCOM & NOSS 3x,Retired,NaN,Success
3001,1,Arianespace,"ELA-2, Guiana Space Centre, French Guiana, France","Tue Oct 29, 1991 23:08 UTC",Ariane 44L | Intelsat 6AF1,Retired,NaN,Success
3002,2,RVSN USSR,"Site 200/39, Baikonur Cosmodrome, Kazakhstan","Wed Oct 23, 1991 15:25 UTC",Proton K/Block-DM-2 | Gorizont 24,Retired,NaN,Success
3003,3,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Thu Oct 17, 1991 00:05 UTC",Soyuz U2 | Progress M-10,Retired,40.0,Success
3004,4,RVSN USSR,"Site 132/1, Plesetsk Cosmodrome, Russia","Thu Oct 10, 1991 14:00 UTC",Cosmos-3M | Cosmos 2164,Retired,NaN,Success
3005,5,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Wed Oct 09, 1991 13:15 UTC",Soyuz U2 | Cosmos 2163,Retired,40.0,Success
3006,6,RVSN USSR,"Site 43/4, Plesetsk Cosmodrome, Russia","Fri Oct 04, 1991 18:09 UTC",Soyuz U | Foton 7,Retired,20.0,Success
3007,7,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Wed Oct 02, 1991 05:59 UTC",Soyuz U2 | Soyuz TM-13,Retired,40.0,Success
3008,8,IAI,"Pad 1, Palmachim Airbase, Israel","Mon Sep 30, 1991",Shavit | Ofek,Retired,NaN,Failure
3009,9,RVSN USSR,"Site 32/2, Plesetsk Cosmodrome, Russia","Sat Sep 28, 1991 07:05 UTC",Tsyklon-3 | Cosmos 2157 to 2162,Retired,NaN,Success

In [34]:
space_missions.iloc[4500:4510]

,Unnamed: 0,Organisation,Location,Datetime,Details,Rocket_Status,Price,Mission_Status
4500,0,NASA,"LA-3, Wallops Flight Facility, Virginia, USA","Sun Feb 18, 1979 16:18 UTC",Scout D1 | Explorer 60 (SAGE),Retired,NaN,Success
4501,1,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia","Fri Feb 16, 1979 15:00 UTC",Soyuz U | Zenit-2M n°447,Retired,20.0,Failure
4502,2,RVSN USSR,"Site 43/4, Plesetsk Cosmodrome, Russia","Tue Feb 13, 1979 21:41 UTC",Vostok-2M | Cosmos 1077,Retired,NaN,Success
4503,3,RVSN USSR,"Site 32/2, Plesetsk Cosmodrome, Russia","Mon Feb 12, 1979 13:00 UTC",Tsyklon-3 | Cosmos 1076,Retired,NaN,Success
4504,4,RVSN USSR,"Site 132/2, Plesetsk Cosmodrome, Russia","Thu Feb 08, 1979 10:00 UTC",Cosmos-3M | Cosmos 1075,Retired,NaN,Success
4505,5,MHI,"LA-Y1, Tanegashima Space Center, Japan","Tue Feb 06, 1979 08:46 UTC",N-I Star-37E | Ayame 1,Retired,NaN,Failure
4506,6,RVSN USSR,"Site 31/6, Baikonur Cosmodrome, Kazakhstan","Wed Jan 31, 1979 09:00 UTC",Soyuz U | Cosmos 1074,Retired,20.0,Success
4507,7,US Air Force,"SLC-17B, Cape Canaveral SFS, Florida, USA","Tue Jan 30, 1979 21:42 UTC",Delta 2914 | SCATHA,Retired,NaN,Success
4508,8,RVSN USSR,"Site 43/4, Plesetsk Cosmodrome, Russia","Tue Jan 30, 1979 15:15 UTC",Soyuz U | Cosmos 1073,Retired,20.0,Success
4509,9,RVSN USSR,"Site 31/6, Baikonur Cosmodrome, Kazakhstan","Thu Jan 25, 1979 05:43 UTC",Vostok-2M | Meteor-Priroda n°3,Retired,NaN,Success

In [35]:
space_missions

,Unnamed: 0,Organisation,Location,Datetime,Details,Rocket_Status,Price,Mission_Status
0,0,VKS RF,"Site 43/4, Plesetsk Cosmodrome, Russia","Fri Feb 09, 2024 07:03 UTC",Soyuz 2.1v | Cosmos 2575,Active,NaN,Success
1,1,SpaceX,"SLC-40, Cape Canaveral SFS, Florida, USA","Thu Feb 08, 2024 06:33 UTC",Falcon 9 Block 5 | PACE,Active,67.0,Success
2,2,CASC,"Bo Run Jiu Zhou Barge (Area 2), China Coastal ...","Sat Feb 03, 2024 03:06 UTC",Jielong-3 | 9 satellites,Active,NaN,Success
3,3,CASC,"LC-3, Xichang Satellite Launch Center, China","Fri Feb 02, 2024 23:37 UTC",Long March 2C | Geely Constellation Group 02,Active,30.8,Success
4,4,Rocket Lab,"Rocket Lab LC-1B, Māhia Peninsula, New Zealand","Wed Jan 31, 2024 06:34 UTC",Electron/Curie | Four Of A Kind,Active,7.5,Success
...,...,...,...,...,...,...,...,...
6706,706,US Navy,"LC-18A, Cape Canaveral SFS, Florida, USA","Wed Feb 05, 1958 07:33 UTC",Vanguard | Vanguard TV3BU,Retired,NaN,Failure
6707,707,ABMA,"LC-26A, Cape Canaveral SFS, Florida, USA","Sat Feb 01, 1958 03:47 UTC",Juno I | Explorer 1,Retired,NaN,Success
6708,708,US Navy,"LC-18A, Cape Canaveral SFS, Florida, USA","Fri Dec 06, 1957 16:44 UTC",Vanguard | Vanguard TV3,Retired,NaN,Failure
6709,709,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Sun Nov 03, 1957 02:30 UTC",Sputnik 8K71PS | Sputnik 2,Retired,NaN,Success
6710,710,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Fri Oct 04, 1957 19:28 UTC",Sputnik 8K71PS | Sputnik 1,Retired,NaN,Success

The rest of the columns contain the following information:

* Organisation *(categorical data)* - which organisation planned and launched the missions.
  
* Location *(categorical data)* - mission launch pad names and location.

* Datetime *(categorical data)* - the date and time of the launches.

* Details *(categorical data)* - has information on the rocket/ space craft names and the missions they were a part of (rocket name | mission name -> that is how they are separated in this column).

* Rocket_Status *(categorical data)* - shows if the rocket, used in the mission, is either "Active" or "Retired".

* Price *(numerical data)* - I'm guessing it's supposed to show how much each mission cost, but there is a lot of missing data and it isn't specified if the numbers are in thousands, millions or other.

* Mission_Status (categorical data) - shows whether the mission was a success or not.

I can see the following actions/changes that need to be done:

* Check for missing values under the remaining columns.
  
* Maybe limit the information, in the location column, to include only the country. I don't see how the launch pads could play a part in my project.

* Standardize the column names to snake_case

* Standardize the dates and remove the times.

* **Remove the rocket status and price columns** -> unneeded for my project analysis.

In [13]:
# Logic to check the column's data types
space_missions_numeric = space_missions.select_dtypes(include=["number"]).columns.tolist()
space_missions_obj_cat = space_missions.select_dtypes(include=["object", "category"]).columns.tolist()
space_missions_bool = space_missions.select_dtypes(include=["bool"]).columns.tolist()

# Print results
print(f"Columns with numeric data are: {space_missions_numeric}")
print(f"Columns with categorical data are: {space_missions_obj_cat}")
print(f"Columns with boolean data are: {space_missions_bool}")

Columns with numeric data are: ['Unnamed: 0', 'Price']
Columns with categorical data are: ['Organisation', 'Location', 'Datetime', 'Details', 'Rocket_Status', 'Mission_Status']
Columns with boolean data are: []

While the majority of the Datetime column's values are like - Wed Feb 05, 1958 07:33 UTC - there are around 15+ cells which provide less information - Sun Jun 26, 2022 (they are missing the time and UTC bit). This lack of a uniform pattern, in the text, along with a later realization that there are cells whith additional spaces, presented a challenge. Ultimately, a new column was created, that had the required date formating.
For the locations, each row had different text length, some had specific regions mentioned or states. I tried to turnicate the text, but the output wasn't what I needed. I then checked the turnicated values for duplicates, created a list with the different countries and used it to achive a column that contained only the country names.

In [98]:
#Altering the original dataset under a new variable, so that I don't lose the first one.
#Removed the unnecessary columns
space_missions_modified = space_missions.drop(columns = ["Unnamed: 0", "Price", "Rocket_Status"])

#Transforming the dates data
# This creates a new column and copies the day and month abbreviations, date, comma and year. It searches for spaces, digit:digit, UTC, spaces 
#and deletes them.
space_missions_modified["date"] = space_missions_modified["Datetime"].str.replace(
    r"\s+\d{2}:\d{2}\s+UTC$", "", regex=True)

#The new date column in turned into actual date-time object (they were strings before). The errors bit is used so that if a cell can't be converted, it 
#becomes NaT (not a time) -> to check if there are any NaT's - space_missions_modified["date"].isna().any(). 
space_missions_modified["date"] = pd.to_datetime(space_missions_modified["date"], errors="coerce")

#Changes how the dates are displayed.
space_missions_modified["date"] = space_missions_modified["date"].dt.strftime("%d/%m/%Y")


#Removes the original Datetime column.
space_missions_modified.drop(columns = ["Datetime"], inplace = True)

#Changes the column titles
space_missions_modified.rename(columns={"Organisation": "organisation", "Location": "country", "Details": "mission_details", "Mission_Status": "mission_status"}, inplace = True)


space_missions_modified

,organisation,country,mission_details,mission_status,date
0,VKS RF,"Site 43/4, Plesetsk Cosmodrome, Russia",Soyuz 2.1v | Cosmos 2575,Success,09/02/2024
1,SpaceX,"SLC-40, Cape Canaveral SFS, Florida, USA",Falcon 9 Block 5 | PACE,Success,08/02/2024
2,CASC,"Bo Run Jiu Zhou Barge (Area 2), China Coastal ...",Jielong-3 | 9 satellites,Success,03/02/2024
3,CASC,"LC-3, Xichang Satellite Launch Center, China",Long March 2C | Geely Constellation Group 02,Success,02/02/2024
4,Rocket Lab,"Rocket Lab LC-1B, Māhia Peninsula, New Zealand",Electron/Curie | Four Of A Kind,Success,31/01/2024
...,...,...,...,...,...
6706,US Navy,"LC-18A, Cape Canaveral SFS, Florida, USA",Vanguard | Vanguard TV3BU,Failure,05/02/1958
6707,ABMA,"LC-26A, Cape Canaveral SFS, Florida, USA",Juno I | Explorer 1,Success,01/02/1958
6708,US Navy,"LC-18A, Cape Canaveral SFS, Florida, USA",Vanguard | Vanguard TV3,Failure,06/12/1957
6709,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",Sputnik 8K71PS | Sputnik 2,Success,03/11/1957
6710,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",Sputnik 8K71PS | Sputnik 1,Success,04/10/1957